server:
    port: 9527

spring:
    application:
        name: cloud-gateway #以微服务注册进consul或nacos服务列表内
    cloud:
        consul: #配置consul地址
            host: localhost
            port: 8500
            discovery:
                prefer-ip-address: true
                service-name: ${spring.application.name}
        gateway:
            routes:
                -   id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#                    uri: http://localhost:8001                #匹配后提供服务的路由地址
                    uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
                    predicates:
                        - Path=/pay/gateway/**              # 断言，路径相匹配的进行路由
#                        - My=diamond
#                        - name: My
#                          args:
#                            userType: diamond
#                        - Method=POST
#                        - RemoteAddr=192.168.2.1/24
#                        - Query=username,\d+
#                        - Host=**.example.com
#                        - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
                        # 在此时间之后可以访问
#                        - After=2024-03-21T11:31:50.230468600+08:00[Asia/Shanghai]
                        # 在此时间之前可以访问
#                        - Before=2024-03-21T11:34:50.230468600+08:00[Asia/Shanghai]
                        # 在此时间段内可以访问
#                        - Between=2024-03-21T11:37:30.230468600+08:00[Asia/Shanghai], 2024-03-21T11:39:00.230468600+08:00[Asia/Shanghai]
#                        - Cookie=username,zzyy
                -   id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
                    uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
                    predicates:
                        - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
                -   id: pay_routh3 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
                    uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
                    predicates:
                        - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
#                        - Path=/gateway/filter/**              # 断言，为配合PrefixPath测试过滤，暂时注释掉/pay
#                        - Path=/XYZ/abc/{segment}              # 断言，为配合PrefixPath测试过滤，暂时注释掉/pay
                    filters:
                        - My=example
#                      - AddRequestHeader=X-Request-example1,exampleValue1111 # 请求头kv，若一头含有多参则重写一行设置
#                      - AddRequestHeader=X-Request-example2,exampleValue2222 # 请求头kv，若一头含有多参则重写一行设置
#                     - RemoveRequestHeader=sec-fetch-site
#                      - SetRequestHeader=sec-fetch-site,java.example.com
#                      - AddRequestParameter=customerId,9517001  # 新增请求参数Parameter：k ，v
#                      - RemoveRequestParameter=customerName # 删除url请求参数customerName，你传递过来也是null
#                      - AddResponseHeader=X-Request-example,BlueResponse # 新增请求参数X-Response-atguigu并设值为BlueResponse
#                      - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
#                      - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除
#                      - PrefixPath=/pay # http://localhost:9527/pay/gateway/filter  被分拆为: PrefixPath + Path
#                      - SetPath=/pay/gateway/{segment} # {segment}表示占位符，你写abc也行但要上下一致
#                      - RedirectTo=302, https://baidu.com/ # 访问http://localhost:9527/pay/gateway/filter跳转到http://www.atguigu.com/


